"""v3.0 expansion: audit_logs, api_keys, schedules, job chaining

Revision ID: 9c6f993670c4
Revises: 3f9f0f1e4d2b
Create Date: 2026-04-05 11:53:51.487537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6f993670c4'
down_revision: Union[str, Sequence[str], None] = '3f9f0f1e4d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('chain_to', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('parent_job_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('worker_name', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_description'), 'jobs', ['description'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_priority'), 'jobs', ['priority'], unique=False)
    op.create_index('ix_jobs_status_scheduled', 'jobs', ['status', 'scheduled_at'], unique=False)
    op.create_index('ix_jobs_user_created', 'jobs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_user_priority', 'jobs', ['user_id', 'priority'], unique=False)
    op.create_index('ix_jobs_user_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_foreign_key(None, 'jobs', 'jobs', ['parent_job_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'jobs', ['chain_to'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index('ix_jobs_user_status', table_name='jobs')
    op.drop_index('ix_jobs_user_priority', table_name='jobs')
    op.drop_index('ix_jobs_user_created', table_name='jobs')
    op.drop_index('ix_jobs_status_scheduled', table_name='jobs')
    op.drop_index(op.f('ix_jobs_priority'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_description'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'worker_name')
    op.drop_column('jobs', 'parent_job_id')
    op.drop_column('jobs', 'chain_to')
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
